apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki-stack
  namespace: logging
spec:
  size: 1x.demo
  limits:
    global:
      ingestion:
        ingestionBurstSize: 16
        ingestionRate: 8
  storage:
    schemas:
    - version: v12
      effectiveDate: "2022-06-01"
    secret:
      name: loki-s3-secret
      type: s3
      credentialMode: static
  storageClassName: gp3-csi
  tenants:
    mode: openshift-logging
