apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/CSA-RH/elk-and-loki-log-management.git'
    path: applications/loki
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
