apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.0.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: oauth-proxy
        image: quay.io/openshift/origin-oauth-proxy:latest
        args:
        - --provider=openshift
        - --openshift-service-account=kibana
        - --upstream=http://127.0.0.1:5601
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --cookie-secret=SECRET
