apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-stack
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/CSA-RH/elk-and-loki-log-management.git'
    path: applications/grafana
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
